# Generated by Django 3.1.1 on 2020-11-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name_plural': 'Pozos'},
        ),
    ]
