# Generated by Django 3.1.1 on 2020-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecStatus', '0003_auto_20201003_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocolumn',
            name='layer',
            field=models.CharField(choices=[('T.A', 'T.A'), ('RPLCN', 'RPLCN'), ('PLCNM', 'PLCNM'), ('PLCNS', 'PLCNS'), ('PLCNI', 'PLCNI'), ('MS', 'MS'), ('YAC-8', 'YAC-8'), ('YAC-7', 'YAC-7'), ('YAC-6', 'YAC-6'), ('YAC-5', 'YAC-5'), ('YAC-4', 'YAC-4'), ('YAC-3', 'YAC-3'), ('YAC-2', 'YAC-2'), ('YAC-1', 'YAC-1')], default='T.A', max_length=7, verbose_name='GeologicalLayer'),
        ),
    ]
