# Generated by Django 3.1.1 on 2020-10-09 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mecStatus', '0004_auto_20201003_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocolumn',
            name='isConnection',
            field=models.BooleanField(default=False, verbose_name='Is Connection'),
        ),
        migrations.AddField(
            model_name='trstate',
            name='isConnection',
            field=models.BooleanField(default=False, verbose_name='Is Connection'),
        ),
        migrations.AlterField(
            model_name='geocolumn',
            name='mecStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoColumns', to='mecStatus.mecstatus', verbose_name='Geological Columns'),
        ),
        migrations.AlterField(
            model_name='trstate',
            name='mecStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trStates', to='mecStatus.mecstatus', verbose_name='TR Status'),
        ),
    ]
