# Generated by Django 3.1.1 on 2020-10-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last    modified', verbose_name='modified')),
                ('orderId', models.IntegerField(default=0, help_text='Specify which is the print order', verbose_name='Identificador de orden')),
                ('startMd', models.FloatField(max_length=10, verbose_name='Inicio Md')),
                ('startTvd', models.FloatField(max_length=10, verbose_name='Inicio Tvd')),
                ('endMd', models.FloatField(max_length=10, verbose_name='Fin Md')),
                ('endTvd', models.FloatField(max_length=10, verbose_name='Fin Tvd')),
                ('programType', models.CharField(choices=[('plan', 'plan'), ('real', 'real')], default='plan', help_text='Determines which program type is', max_length=4, verbose_name='Tipo de programa')),
                ('pipeDiameter', models.CharField(choices=[('20', '20'), ('13 3/8', '13 3/8'), ('9 5/8', '9 5/8'), ('7', '7')], default='20', help_text='External pipe diameter', max_length=7, verbose_name='Diametro de tuberia')),
                ('drillDiameter', models.CharField(choices=[('26', '26'), ('16', '16'), ('12 1/4', '12 1/4'), ('8 1/2', '8 1/2')], default='26', help_text='Drill diameter', max_length=7, verbose_name='Diametro de barrena')),
                ('isConnection', models.BooleanField(default=False, help_text='The pipe is a connection?', verbose_name='Conexion')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trStatus', to='clusters.well', verbose_name='Estado mecanico TR')),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last    modified', verbose_name='modified')),
                ('orderId', models.IntegerField(default=0, help_text='Specify which is the print order', verbose_name='Identificador de orden')),
                ('startMd', models.FloatField(max_length=10, verbose_name='Inicio Md')),
                ('startTvd', models.FloatField(max_length=10, verbose_name='Inicio Tvd')),
                ('endMd', models.FloatField(max_length=10, verbose_name='Fin Md')),
                ('endTvd', models.FloatField(max_length=10, verbose_name='Fin Tvd')),
                ('programType', models.CharField(choices=[('plan', 'plan'), ('real', 'real')], default='plan', help_text='Determines which program type is', max_length=4, verbose_name='Tipo de programa')),
                ('layer', models.CharField(choices=[('T.A', 'T.A'), ('RPLCN', 'RPLCN'), ('PLCNM', 'PLCNM'), ('PLCNS', 'PLCNS'), ('PLCNI', 'PLCNI'), ('MS', 'MS'), ('YAC-8', 'YAC-8'), ('YAC-7', 'YAC-7'), ('YAC-6', 'YAC-6'), ('YAC-5', 'YAC-5'), ('YAC-4', 'YAC-4'), ('YAC-3', 'YAC-3'), ('YAC-2', 'YAC-2'), ('YAC-1', 'YAC-1')], default='T.A', max_length=7, verbose_name='Columna geologica')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoColumns', to='clusters.well', verbose_name='Pozo')),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
