# Generated by Django 3.1.1 on 2020-11-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocolumn',
            options={'verbose_name_plural': 'Columnas geologicas'},
        ),
        migrations.AlterModelOptions(
            name='trstate',
            options={'verbose_name_plural': 'Estados mecanicos'},
        ),
    ]
