# Generated by Django 3.1.1 on 2020-09-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mecStatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecstatus',
            name='well',
        ),
        migrations.AddField(
            model_name='mecstatus',
            name='name',
            field=models.CharField(default=None, max_length=12, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='geocolumn',
            name='mecStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geoColumns', to='mecStatus.mecstatus'),
        ),
        migrations.AlterField(
            model_name='trstate',
            name='mecStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trStates', to='mecStatus.mecstatus'),
        ),
    ]
